name: news_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: any
  flutter_bloc: any
  font_awesome_flutter: any
  dio: ^5.4.0
  conditional_builder_null_safety: ^0.0.6
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  webview_flutter: ^4.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true
